use_frameworks!

platform :ios, '9.0'

target 'WXShareToolKit_Example' do
  pod 'WXShareToolKit', :path => '../'

  target 'WXShareToolKit_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
